/* Fallback local explícito para ?demo=1 o file://. No contiene stock ni clientes ficticios. */
(function () {
  'use strict';
  const C = window.StockCatalog;
  const KEY = 'nexo_stock_local_empty_v2';
  const SESSION = 'nexo_stock_local_session_v2';
  const get = key => { try { return localStorage.getItem(key); } catch (_) { return null; } };
  const set = (key, value) => { try { localStorage.setItem(key, value); } catch (_) {} };
  const remove = key => { try { localStorage.removeItem(key); } catch (_) {} };
  const now = () => new Date().toISOString();
  const today = () => now().slice(0, 10);
  const id = prefix => `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
  const clone = value => JSON.parse(JSON.stringify(value));
  const number = value => Number(value) || 0;
  const round = value => Math.round(number(value) * 100) / 100;
  const initials = value => String(value || 'NA').split(/\s+/).filter(Boolean).map(part => part[0]).join('').slice(0, 2).toUpperCase();
  const hash = value => { let h = 2166136261; for (let i = 0; i < String(value).length; i += 1) { h ^= String(value).charCodeAt(i); h = Math.imul(h, 16777619); } return `local$${(h >>> 0).toString(16)}`; };
  const normalizeImei = value => String(value || '').replace(/[\s-]/g, '').toUpperCase();
  const validImei = value => { const imei = normalizeImei(value); if (!/^\d{15}$/.test(imei)) return false; let sum = 0; for (let i = 0; i < 14; i += 1) { let digit = Number(imei[i]); if (i % 2) { digit *= 2; if (digit > 9) digit -= 9; } sum += digit; } return (10 - (sum % 10)) % 10 === Number(imei[14]); };

  function emptyState() {
    return {
      version: 2,
      settings: { businessName: 'NEXO Móviles', legalName: '', currency: 'USD', locale: 'es-AR', locationName: 'Córdoba Capital', valuationMethod: 'AVERAGE', minMargin: 0, defaultMinStock: 1, lastUnitThreshold: 1, allowNegativeStock: false, lowStockNotifications: true, publicShowApplePrice: false, lastBackup: null },
      users: [{ id: 'usr_admin', name: 'Administrador local', email: 'admin@nexo.com', role: 'Administrador', active: true, passwordHash: hash('admin123'), avatar: 'AD', lastLogin: '' }],
      suppliers: [], customers: [], products: [], units: [], sales: [], returns: [], purchases: [], movements: [], reservations: [], warrantyClaims: [], auditLogs: [], errorLogs: [],
      paymentMethods: [...C.paymentMethods], categories: [...C.categories], locations: ['Córdoba Capital'], capacities: [...C.capacities], colors: [...C.colors], brands: ['Apple', ...C.otherBrands]
    };
  }

  class LocalStore {
    constructor() { this.userId = null; this.state = this.load(); ['addStock', 'removeStock', 'createSale', 'createPurchase'].forEach(name => { const original = this[name].bind(this); this[name] = async (...args) => { const snapshot = clone(this.state); try { return await original(...args); } catch (error) { this.state = snapshot; throw error; } }; }); }
    load() { try { const parsed = JSON.parse(get(KEY) || 'null'); if (parsed?.version === 2) return parsed; } catch (_) {} this.state = emptyState(); this.save(); return this.state; }
    save() { set(KEY, JSON.stringify(this.state)); }
    getState() { return this.state; }
    getSettings() { return this.state.settings; }
    getProducts(all = false) { return this.state.products.filter(product => all || product.status !== 'Archivado'); }
    getProduct(id) { return this.state.products.find(product => product.id === id); }
    getUnit(id) { return this.state.units.find(unit => unit.id === id); }
    getUser(id) { return this.state.users.find(user => user.id === id); }
    getSupplier(id) { return this.state.suppliers.find(item => item.id === id); }
    getCustomer(id) { return this.state.customers.find(item => item.id === id); }
    getSessionUser() { return this.getUser(this.userId); }
    isAuthenticated() { return Boolean(this.getSessionUser()); }
    isDuplicateImei(imei, ignore = null) { const value = normalizeImei(imei); return this.state.units.find(unit => unit.id !== ignore && normalizeImei(unit.imei) === value) || null; }
    async init() { try { const session = JSON.parse(get(SESSION) || 'null'); this.userId = session?.userId || null; } catch (_) { this.userId = null; } if (!this.getSessionUser()) return this.login('admin@nexo.com', 'admin123'); return this.getSessionUser(); }
    async login(email, password) { const user = this.state.users.find(item => item.email.toLowerCase() === String(email).toLowerCase()); if (!user || user.passwordHash !== hash(password)) throw new Error('Credenciales incorrectas.'); this.userId = user.id; user.lastLogin = now(); set(SESSION, JSON.stringify({ userId: user.id })); this.save(); return user; }
    async logout() { this.userId = null; remove(SESSION); }
    async refresh() { return this.state; }
    audit(action, entity, before = '', after = '') { this.state.auditLogs.unshift({ id: id('aud'), userId: this.userId || 'usr_admin', action, entity, before: String(before), after: String(after), createdAt: now() }); }
    normalize(input, old = {}) { const costSupplied = Object.hasOwn(input, 'cost') && input.cost !== ''; const cost = costSupplied ? round(input.cost) : number(old.cost); const priceSupplied = Object.hasOwn(input, 'price') && input.price !== ''; const price = priceSupplied ? round(input.price) : number(old.price); return { brand: String(input.brand ?? old.brand ?? '').trim(), model: String(input.model ?? old.model ?? '').trim(), category: String(input.category ?? old.category ?? 'Otros').trim(), variant: String(input.variant ?? old.variant ?? (`${input.capacity || old.capacity || ''}${input.capacity || old.capacity ? ' · ' : ''}${input.color || old.color || ''}` || 'Estándar')).trim(), capacity: String(input.capacity ?? old.capacity ?? ''), color: String(input.color ?? old.color ?? ''), ram: String(input.ram ?? old.ram ?? ''), condition: input.condition || old.condition || 'Nuevo', physicalState: input.physicalState || old.physicalState || '10/10', requiresImei: Object.hasOwn(input, 'requiresImei') ? Boolean(input.requiresImei) : old.requiresImei !== false, cost, costKnown: Object.hasOwn(input, 'costRegistered') ? Boolean(input.costRegistered) : old.costKnown ?? costSupplied, price, salePriceKnown: Object.hasOwn(input, 'salePriceRegistered') ? Boolean(input.salePriceRegistered) : old.salePriceKnown ?? priceSupplied, promoPrice: input.promoPrice ? round(input.promoPrice) : old.promoPrice || null, appleOfficialPriceUsd: input.appleOfficialPriceUsd === '' ? null : round(input.appleOfficialPriceUsd ?? old.appleOfficialPriceUsd), applePriceSource: input.applePriceSource ?? old.applePriceSource ?? '', minStock: Math.max(0, Number(input.minStock ?? old.minStock ?? this.state.settings.defaultMinStock) || 0), supplierId: input.supplierId ?? old.supplierId ?? '', location: input.location || old.location || this.state.settings.locationName, purchaseDate: input.purchaseDate || old.purchaseDate || '', warranty: input.warranty ?? old.warranty ?? '', notes: input.notes ?? old.notes ?? '', barcode: input.barcode ?? old.barcode ?? '', sku: input.sku || old.sku || `LOCAL-${Date.now().toString(36).toUpperCase()}` }; }
    async addProduct(input) { if (!input.brand || !input.model) throw new Error('Indicá marca y modelo.'); const product = { id: id('variant'), productId: id('product'), ...this.normalize(input), stock: 0, availableStock: 0, reservedStock: 0, status: 'Activo', createdAt: now(), updatedAt: now() }; this.state.products.unshift(product); this.audit('Producto creado', product.id, '', product.sku); this.save(); return product; }
    async createVariant(parentId, input) { const sibling = this.state.products.find(product => product.productId === parentId); if (!sibling) throw new Error('Producto padre no encontrado.'); return this.addProduct({ ...sibling, ...input }); }
    async updateProduct(pid, input) { const product = this.getProduct(pid); if (!product) throw new Error('Producto no encontrado.'); Object.assign(product, this.normalize({ ...product, ...input }, product), { updatedAt: now() }); this.audit('Producto actualizado', pid, '', product.sku); this.save(); return product; }
    async archiveProduct(pid) { const product = this.getProduct(pid); if (!product) throw new Error('Producto no encontrado.'); if (product.stock > 0) throw new Error('No se puede archivar un producto con stock.'); product.status = 'Archivado'; this.audit('Producto archivado', pid); this.save(); return product; }
    async addStock(input) { const product = this.getProduct(input.productId); if (!product) throw new Error('Producto no encontrado.'); const quantity = Math.floor(Number(input.quantity)); const imeis = (input.imeis || []).map(normalizeImei).filter(Boolean); if (!Number.isInteger(quantity) || quantity < 1) throw new Error('Cantidad inválida.'); if (product.requiresImei && imeis.length !== quantity) throw new Error(`Ingresá ${quantity} IMEI(s).`); if (!product.requiresImei && imeis.length) throw new Error('Este producto no maneja IMEI.'); imeis.forEach(imei => { if (!validImei(imei)) throw new Error(`IMEI inválido: ${imei}.`); if (this.isDuplicateImei(imei)) throw new Error('Este IMEI ya está registrado.'); }); const before = product.stock; product.stock += quantity; product.availableStock = product.stock; if (Object.hasOwn(input, 'unitCost') && input.unitCost !== '') { product.cost = round(input.unitCost); product.costKnown = true; } (input.imeis || []).forEach((imei, index) => this.state.units.push({ id: id('unit'), productId: product.id, imei, imei2: '', serialNumber: input.serialNumbers?.[index] || '', status: 'Disponible', condition: product.condition, physicalState: product.physicalState, cost: product.costKnown ? product.cost : null, costKnown: product.costKnown, salePrice: product.salePriceKnown ? product.price : null, entryDate: today(), supplierId: product.supplierId, location: product.location, notes: '' })); this.state.movements.unshift({ id: id('mov'), date: now(), userId: this.userId, productId: product.id, type: 'Entrada', quantity, stockBefore: before, stockAfter: product.stock, reason: input.reason || 'Ingreso de stock', cost: product.costKnown ? product.cost : null, createdAt: now() }); this.audit('Stock agregado', product.id, before, product.stock); this.save(); return product; }
    async removeStock(input) { const product = this.getProduct(input.productId); if (!product) throw new Error('Producto no encontrado.'); const quantity = Math.floor(Number(input.quantity)); if (!Number.isInteger(quantity) || quantity < 1 || product.stock < quantity) throw new Error('Stock insuficiente.'); const reason = String(input.reason || '').trim(); if (!reason) throw new Error('Indicá el motivo de la salida.'); const before = product.stock; const selected = input.unitIds || []; if (product.requiresImei && selected.length !== quantity) throw new Error('Seleccioná las unidades correctas.'); const units = selected.length ? selected.map(unitId => this.getUnit(unitId)) : this.state.units.filter(unit => unit.productId === product.id && unit.status === 'Disponible').slice(0, quantity); if (product.requiresImei && units.some(unit => !unit || unit.status !== 'Disponible')) throw new Error('Unidad no disponible.'); units.forEach(unit => { if (unit) unit.status = input.type === 'Pérdida' ? 'Perdido' : 'Retirado'; }); product.stock -= quantity; product.availableStock = product.stock; this.state.movements.unshift({ id: id('mov'), date: now(), userId: this.userId, productId: product.id, type: input.type || 'Salida manual', quantity: -quantity, stockBefore: before, stockAfter: product.stock, reason, cost: product.costKnown ? product.cost : null, createdAt: now() }); this.audit('Stock retirado', product.id, before, product.stock); this.save(); return product; }
    async createSale(input) { if (!input.items?.length) throw new Error('Agregá al menos un producto.'); if (input.customerId && !this.getCustomer(input.customerId)) throw new Error('El cliente seleccionado no existe.'); const used = new Set(); const items = []; let total = 0; let cost = 0; let profitKnown = true; for (const raw of input.items) { const product = this.getProduct(raw.productId); const quantity = Math.floor(Number(raw.quantity)); if (!product || !Number.isInteger(quantity) || quantity < 1 || product.availableStock < quantity) throw new Error('Stock insuficiente.'); const price = round(raw.price ?? product.price); if (!(price > 0)) throw new Error('La variante no tiene precio de venta registrado.'); let unit = null; if (product.requiresImei) { if (quantity !== 1 || !raw.unitId) throw new Error('Seleccioná una unidad disponible.'); unit = this.getUnit(raw.unitId); if (!unit || unit.productId !== product.id || unit.status !== 'Disponible' || used.has(unit.id)) throw new Error('Unidad no disponible.'); used.add(unit.id); } const line = { productId: product.id, productName: `${product.brand} ${product.model}`, variant: product.variant, quantity, unitId: unit?.id || '', imei: unit?.imei || '', price, discount: round(raw.discount || 0), total: round(quantity * price - (raw.discount || 0)), cost: product.costKnown ? product.cost : null, costKnown: product.costKnown }; if (line.total <= 0) throw new Error('Descuento inválido.'); items.push(line); total += line.total; if (!line.costKnown) profitKnown = false; else cost += line.cost * quantity; product.stock -= quantity; product.availableStock -= quantity; if (unit) { unit.status = 'Vendido'; unit.salePrice = price; } this.state.movements.unshift({ id: id('mov'), date: now(), userId: this.userId, productId: product.id, unitId: unit?.id || '', type: 'Venta', quantity: -quantity, stockBefore: product.stock + quantity, stockAfter: product.stock, cost: line.cost, price, reason: 'Venta registrada', createdAt: now() }); } const discount = round(input.discount || 0); total = round(total - discount); if (total <= 0) throw new Error('Total inválido.'); const sale = { id: id('sale'), date: input.date || now(), customerId: input.customerId || '', customerName: this.getCustomer(input.customerId)?.name || 'Cliente mostrador', items, total, cost: profitKnown ? round(cost) : null, profit: profitKnown ? round(total - cost) : null, profitKnown, paymentMethod: input.paymentMethod || 'Efectivo', paymentStatus: 'Pagada', status: 'ACTIVA', statusCode: 'ACTIVE', userId: this.userId, notes: input.notes || '', discount }; this.state.sales.unshift(sale); this.audit('Venta registrada', sale.id, '', total); this.save(); return sale; }
    async annulSale(saleId, input) { const sale = this.state.sales.find(item => item.id === saleId); if (!sale) throw new Error('Venta no encontrada.'); if (sale.statusCode === 'ANNULLED') return sale; if (!String(input.reason || '').trim()) throw new Error('Indicá el motivo.'); sale.items.forEach(item => { const product = this.getProduct(item.productId); product.stock += item.quantity; product.availableStock += item.quantity; if (item.unitId) { const unit = this.getUnit(item.unitId); if (unit) unit.status = 'Disponible'; } this.state.movements.unshift({ id: id('mov'), date: now(), userId: this.userId, productId: item.productId, unitId: item.unitId, type: 'Devolución', quantity: item.quantity, stockBefore: product.stock - item.quantity, stockAfter: product.stock, reason: `Anulación: ${input.reason}`, createdAt: now() }); }); sale.status = 'ANULADA'; sale.statusCode = 'ANNULLED'; sale.annulReason = input.reason; this.audit('Venta anulada', sale.id, 'ACTIVA', 'ANULADA'); this.save(); return sale; }
    async createReturn() { throw new Error('Las devoluciones requieren el servidor activo.'); }
    async createPurchase(input) { if (!input.supplierId || !this.getSupplier(input.supplierId)) throw new Error('Seleccioná un proveedor válido.'); let total = 0; for (const item of input.items || []) { const product = this.getProduct(item.productId); if (!product) throw new Error('Producto no encontrado.'); const quantity = Number(item.quantity); const cost = round(item.unitCost); if (!Number.isInteger(quantity) || quantity < 1 || !(cost >= 0)) throw new Error('Cantidad o costo inválido.'); const imeis = (item.imeis || []).map(normalizeImei).filter(Boolean); if (product.requiresImei && imeis.length !== quantity) throw new Error('Faltan IMEI.'); imeis.forEach(imei => { if (!validImei(imei) || this.isDuplicateImei(imei)) throw new Error('IMEI inválido o duplicado.'); }); product.stock += quantity; product.availableStock += quantity; product.cost = round(((product.stock - quantity) * (product.costKnown ? product.cost : 0) + quantity * cost) / product.stock); product.costKnown = true; imeis.forEach(imei => this.state.units.push({ id: id('unit'), productId: product.id, imei, status: 'Disponible', cost, costKnown: true, salePrice: product.salePriceKnown ? product.price : null, entryDate: today(), location: product.location, supplierId: input.supplierId })); this.state.movements.unshift({ id: id('mov'), date: input.date || now(), userId: this.userId, productId: product.id, type: 'Entrada', quantity, stockBefore: product.stock - quantity, stockAfter: product.stock, cost, reason: 'Compra a proveedor', createdAt: now() }); total += quantity * cost; } const purchase = { id: id('purchase'), date: input.date || now(), supplierId: input.supplierId, supplierName: this.getSupplier(input.supplierId).name, items: input.items || [], total: round(total), paymentMethod: input.paymentMethod || 'Transferencia', paymentStatus: input.paymentStatus || 'Pagada', userId: this.userId }; this.state.purchases.unshift(purchase); this.audit('Compra registrada', purchase.id, '', total); this.save(); return purchase; }
    async createCustomer(input) { const taxId = String(input.taxId || '').replace(/[^0-9A-Za-z]/g, '').toUpperCase(); if (taxId && this.state.customers.some(customer => String(customer.taxId || '').replace(/[^0-9A-Za-z]/g, '').toUpperCase() === taxId)) throw new Error('Ya existe un cliente con este DNI.'); const row = { id: id('customer'), name: String(input.name || `${input.firstName || ''} ${input.lastName || ''}`.trim()).trim(), firstName: input.firstName || '', lastName: input.lastName || '', taxId: input.taxId || '', phone: input.phone || '', whatsapp: input.whatsapp || '', email: input.email || '', address: input.address || '', notes: input.notes || '', createdAt: now() }; if (!row.name) throw new Error('Ingresá el nombre.'); this.state.customers.unshift(row); this.save(); return row; }
    async updateCustomer(cid, input) { const row = this.getCustomer(cid); if (!row) throw new Error('Cliente no encontrado.'); Object.assign(row, input); this.save(); return row; }
    async createSupplier(input) { const row = { id: id('supplier'), name: String(input.name || '').trim(), company: input.company || '', taxId: input.taxId || '', phone: input.phone || '', whatsapp: input.whatsapp || '', email: input.email || '', address: input.address || '', notes: input.notes || '', createdAt: now() }; if (!row.name) throw new Error('Ingresá el nombre.'); this.state.suppliers.unshift(row); this.save(); return row; }
    async updateSupplier(sid, input) { const row = this.getSupplier(sid); if (!row) throw new Error('Proveedor no encontrado.'); Object.assign(row, input); this.save(); return row; }
    async createReservation(input) { const unit = this.getUnit(input.unitId); if (!unit || unit.status !== 'Disponible') throw new Error('La unidad no está disponible.'); unit.status = 'Reservado'; const row = { id: id('reservation'), productId: unit.productId, unitId: unit.id, customerId: input.customerId, customerName: this.getCustomer(input.customerId)?.name || '', createdAt: now(), expiresAt: input.expiresAt || '', deposit: Number(input.deposit || 0), status: 'Activa', notes: input.notes || '' }; this.state.reservations.unshift(row); this.save(); return row; }
    async releaseReservation(rid) { const row = this.state.reservations.find(item => item.id === rid); if (row) { const unit = this.getUnit(row.unitId); if (unit) unit.status = 'Disponible'; row.status = 'Cancelada'; this.save(); } return row; }
    async updateSettings(input) { Object.assign(this.state.settings, input); this.save(); return this.state.settings; }
    async addOption(key, value) { const map = { brands: 'brands', colors: 'colors', capacities: 'capacities', locations: 'locations', categories: 'categories', paymentMethods: 'paymentMethods', models: 'brands' }; const target = map[key] || key; if (!this.state[target]) this.state[target] = []; if (!this.state[target].includes(value)) this.state[target].push(value); this.save(); }
    async removeOption(key, value) { const target = key === 'paymentMethods' ? 'paymentMethods' : key; this.state[target] = (this.state[target] || []).filter(item => item !== value); this.save(); }
    async importProducts(rows) { for (const row of rows || []) await this.addProduct(row); return { imported: (rows || []).length }; }
    async exportData() { return clone(this.state); }
    async importData(value) { const data = typeof value === 'string' ? JSON.parse(value) : value; this.state = data?.data || data; this.save(); }
    async reset() { this.state = emptyState(); this.userId = null; remove(SESSION); this.save(); }
    getMetrics() { const sales = this.state.sales.filter(sale => sale.statusCode !== 'ANNULLED'); const costKnown = sales.every(sale => sale.profitKnown !== false); return { stockValue: this.state.products.reduce((sum, product) => sum + product.stock * (product.costKnown ? product.cost : 0), 0), retailValue: this.state.products.reduce((sum, product) => sum + product.stock * (product.salePriceKnown ? product.price : 0), 0), units: this.state.products.reduce((sum, product) => sum + product.stock, 0), productCount: this.state.products.length, lowStock: this.state.products.filter(product => product.stock > 0 && product.stock <= product.minStock).length, outOfStock: this.state.products.filter(product => product.stock === 0).length, potentialProfit: null, salesDay: 0, salesMonth: sales.reduce((sum, sale) => sum + sale.total, 0), previousSalesMonth: 0, salesTrendPercent: null, profitDay: costKnown ? sales.reduce((sum, sale) => sum + (sale.profit || 0), 0) : null, profitMonth: costKnown ? sales.reduce((sum, sale) => sum + (sale.profit || 0), 0) : null, purchasesMonth: 0, unitsSoldMonth: sales.reduce((sum, sale) => sum + sale.items.reduce((n, item) => n + item.quantity, 0), 0) }; }
    getTopProducts() { return []; }
    getDailySeries(days = 7) { return Array.from({ length: days }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (days - index - 1)); return { key: date.toISOString().slice(0, 10), label: date.toLocaleDateString('es-AR', { weekday: 'short' }), sales: 0, profit: 0, purchases: 0 }; }); }
    search(query = '') { const q = String(query).toLowerCase().trim(); return this.getProducts().filter(product => !q || `${product.brand} ${product.model} ${product.variant} ${product.sku}`.toLowerCase().includes(q) || this.state.units.some(unit => unit.productId === product.id && String(unit.imei).includes(q.replace(/\s/g, '')))); }
  }
  if (window.location.protocol === 'file:' || window.location.search.includes('demo=1')) { window.NEXO_LOCAL_MODE = true; window.StockStore = new LocalStore(); }
})();
